name: deploy.ia

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Copiar arquivos para VPS
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        ARGS: "-avz"
        SOURCE: "./"
        REMOTE_HOST: ${{vars.REMOTE_HOST}}
        REMOTE_USER: ${{vars.REMOTE_USER}}
        REMOTE_PORT: ${{vars.REMOTE_PORT}}
        TARGET: ${{vars.TARGET_DEVELOPMENT}}

    - name: Ajustar permissões
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ vars.REMOTE_HOST }}
        username: ${{ vars.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ vars.REMOTE_PORT }}
        script: |
            sudo chown -R www-data:www-data ${{ vars.TARGET_DEVELOPMENT }}
            sudo chmod -R 775 ${{ vars.TARGET_DEVELOPMENT }}/storage
            sudo chmod -R 775 ${{ vars.TARGET_DEVELOPMENT }}/bootstrap/cache

    - name: Pós-deploy (instalar dependências e restart)
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ vars.REMOTE_HOST }}
        username: ${{ vars.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ vars.REMOTE_PORT }}
        script: |
            cd ${{ vars.TARGET_DEVELOPMENT }}
            # Ative o ambiente virtual e instale dependências, se necessário
            source venv/bin/activate && pip install -r requirements.txt
            sudo systemctl restart minha-api.service
